---
params:
  reads: "/data/SGSlab/20240213/"
  output: "/data/SGSlab/NIH-COV2/20240213/"
  ref: "/data/SGSlab/reference_files/virus/sars2/SARS-CoV2.fa"
  adapters: "/usr/local/apps/trimmomatic/0.39/adapters/NexteraPE-PE.fa"
  primers_bed: "/data/SGSlab/NIH-COV2/primers/nCoV-2019.artic_v4.primer.bed"
  primers_a: "/data/SGSlab/NIH-COV2/primers/nCoV-2019.artic_v4.A.fa"
  primers_b: "/data/SGSlab/NIH-COV2/primers/nCoV-2019.artic_v4.B.fa"
  pl: "illumina"
  pm: "miseq"
  fcid: "000000000-CP3RN"
  cov_cutoff: "10"

timo_params:
  strain: "COV19"
  contig: "NC_045512.2"
  freq_cutoff: "0.001"
  features: "/data/SGSlab/mchung/pipelines/covid_snakemake/timo/sars-cov-2-features.5.csv"
